language: node_js

node_js:
- '8'
- '9'
- '10'

# Use container-based Travis infrastructure.
sudo: false

branches:
  only:
  - master
  - "/^greenkeeper/.*$/"

env:
  global:
  - secure: "hna6dzXQ2XM0VuXmJWbvhbbZrpGn+tMeKPXR57uyqIU5Q8XZii23LcD5wfiD3elUvPYzOgFJevfIbiMskXNsDqNuky+OBD4B29yQc6wGeUk3WuH2t193m3jMZnn4pJqtyc4IzIQoSdZ5yp6Y7v3YgU/rvAWdm0SLdl6PXvHa6Sejq6fLpNxZGB8ZaGU0xbFecsPfwoDHJB6dHTy3Z8TYWwPzjLbwTDb05WOaauQj8CnCkoYxY/8e06IXPhsKX1z43d2S6t6iCsXoBcXcfspnBC4R0M1BPnNdQGCNMjnYsfXp/Mcawy7udUHW4n4Vm+kT108WFhWwf0YwVa6uXMlv28uaQaGU+nh1YtsI1zRezFotyEzjgL8NYyD46b9WgpDLwdoFyjKfcln9KX9bJazQXlUq/o/k0W1THJsxKUy1oHDrltTDMNjDahMiIo1J6q3SFvBTZoZXMdmHxqXvdxxeAH922cVMEEiNa1rllMGuYBmB88gvJD7XJMGrnh44bNjgoVYghuIH29wAA5fRfXPFoEL5jEjcPJFxTloD/y2GUGUVa2L9yYb+i2LEd/+2EFu2ZHPlcjkIAwiHjtZDkTjPM1xIYKKHBUtigD7YXGSptWVnUeCaWsnLt40nmuqapbXytNLUcsecnuD+KBlfSr2KwAnhR3/0J0+x3MPTQOoMVWs="
  - secure: "j859hh4K5xNPhp+x85jFb+cprniC0jcY/5bs3UA8iRLEFkEMpBcbGfaeKUb24p+viRCxVqFUXl2HNyGI5NLWynsDHgiD+hjrTTqs3FclOqmq3xQ2twwDhpwq4YGIIxeXQL5Sy+z/E8cxmyyqjNFwZW0Ywn39aOisMrzujsJ/MJxYKIPTvK3Qnwq88sVyGMzMVvt09dpbiWzZJoWxRVMSu4fcT5GW1hsEnJ3hLuVFCrAgLWIRV82S6ZPJTtlsBaEYiCAVLjzDV7qU6Zj7BCa/Q2YTWP1OJ2KoI6a3RpLVnLPRsT7cwIwAK1s54jKnXfZI6SltYZLlLHqU8v/UjVOJD1qnk5AXC5qSTIYW8nKHtUFNJwFfxeaElLrt8o/X0SMkCQjRKV4DSjMJpou1+5GD39LLkHLojbZpbqU78eGPBFKpzDoPK8L49F/tLqB8xLWcokgWClwjPiCrLj5596ADnNT/jLtm7UOmHGqig7s63YbO19UBuIlDjrKMLP4BgIU60x3NTw3+1HBdFtEKSE98jS5+w5epR/LcHl6D8rX+yLZpLvMpouPjQaW0ncQtkWuf3HaSUptEVtEm+7Bzs5Zd78SQ5Po2MbV63K9qn5vnQWQWiUPS3Cu9cU4VtLLifP3qbSW89RJQuTC7J8w7ZafcBBtJVU2uv/YMwfoo2m1wbHQ="

script:
- yarn test

after_success:
- $(yarn bin)/nyc report --reporter=text-lcov | $(yarn bin)/coveralls
- bash <(curl -s https://codecov.io/bash)
